openapi: "3.0.0"
info:
  version: 1.0.0
  title: APIQL API
  description: An API to create custom REST-like APIs from a graphQL API
servers:
  - url: http://localhost:8080/apiql
paths:
  /apiql/apis:
    get:
      description: Returns a list of APIs
      operationId: listAPIs

  /apiql/apis/{name}:
    put:
      description: Adds or updates an API
      operationId: createOrUpdateAPI
      parameters:
      - name: name
        in: path
        description: name of the API
        required: true
        schema:
          type: string
      requestBody:
        description: OpenAPI 3.0 API Description document
        required: true
        content:
          application/openapi+json:
            schema:
              type: object
            example: |
              {
                "openapi": "3.0.0",
                "info": {
                  "version": "1.0.0",
                  "title": "Star Wars REST resource API",
                  "description": "A sample API converting graphQL to ad hoc REST resource APIs"
                },
                "servers": [
                  {
                    "url": "http://localhost:3000"
                  }
                ],
                "paths": {
                    "/droids/{id}": {
                      "get": {
                          "description": "Returns a Droid"
                      }
                    }
                  }
                }       
          application/openapi+yaml:
              schema:
                type: string
              example: |
                openapi: 3.0.0
                info:
                  version: 1.0.0
                  title: Star Wars REST resource API
                  description: A sample API converting graphQL to ad hoc REST resource APIs
                servers:
                  - url: 'http://localhost:3000'
                paths:
                  '/droids/{id}':
                    get:
                      description: Returns a Droid
              
          
              
    get:
      description: Shows API. Supports conneg.
      operationId: getAPI
      parameters:
      - name: name
        in: path
        description: name of the API
        required: true
        schema:
          type: string
    delete:
      description: Shows API
      operationId: deleteAPI
      parameters:
      - name: name
        in: path
        description: name of the API
        required: true
        schema:
          type: string
  /apiql/description:
    get:
      description: Shows the documentation for the apiql APIs.
