apiVersion: v1
kind: Service
metadata:
  name: star-wars-server
  labels:
    app: star-wars
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: star-wars
    tier: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-wars-server
  labels:
    app: star-wars
    tier: backend
spec:
  selector:
    matchLabels:
      app: star-wars
      tier: backend
  replicas: 2
  template:
    metadata:
      name: star-wars-server
      labels:
        app: star-wars
        tier: backend
    spec:
      containers:
      - name: star-wars
        image: fosrias/star-wars-server:latest
        resources:
            requests:
              cpu: 100m
              memory: 100Mi
        ports:
        - containerPort: 8080
